Adding support for Sorani Kurdish
Belval/TextRecognitionDataGenerator pull request #273
Opened 2022-06-22 16:01 UTC by Hrazhan

The current RTL implementation does not support Kurdish letters which is a type of Arabic script. Since TRDG uses the arabic-reshaper library, I could easily solve this by passing the "language" parameter to the ArabicReshaper class. 

- Along with the RTL parameter to True `--language` parameter  should be set to "ckb"
- I also added a dictionary of Kurdish words
- Wrote a test function with a font supporting Kurdish letters

2022-06-27 02:12 UTC, Belval requested changes
Overall I'd be inclined to merge this feature. Please address my comment.

2022-06-27 02:12 UTC, Belval commented on trdg/generators/from_strings.py
> +from numpy.lib.function_base import delete
Is this used anywhere?

2022-06-27 14:41 UTC, Hrazhan commented on trdg/generators/from_strings.py
> +from numpy.lib.function_base import delete
Hey, I haven't used that anywhere

2022-07-12 05:24 UTC, SilvaQ commented
@Belval 
ug 语言的生成也需要这个PR， 我暂先本地调整了，望早点合并

2022-07-18 11:43 UTC, Belval approved these changes

2022-07-18 11:44 UTC, Belval commented
Will test and merge this week, thank you for your contribution!

2022-08-01 21:35 UTC, merged

2022-08-01 21:35 UTC, Belval commented
Thank you for your contribution.